name: Deploy to Heroku

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Set up Heroku API Key
        run: echo "HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }}" >> $GITHUB_ENV

      - name: Login to Heroku
        run: |
          echo ${{ secrets.HEROKU_API_KEY }} | heroku auth:token

      - name: Set Heroku stack to container
        run: heroku stack:set container --app boston-house-price-prediction1

      - name: Build Docker image and push to Heroku
        run: |
          heroku container:push web --app boston-house-price-prediction1

      - name: Release Docker container
        run: heroku container:release web --app boston-house-price-prediction1
