name: Deploy to heroku.

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuitThe job failed because the Heroku stack is not set to `container`.

Here's an updated workflow file with the/heroku-docker-deploy@v1.3.3
        with:
          correct steps:

```yaml
name: Deploy to heroku.

 email: ${{ secrets.HEROKU_EMAIL }}
          heron:
  push:
    branches: [main]

jobs:
  build:
oku_api_key: ${{ secrets.HEROKU_API_KEY }}
          her    runs-on: ubuntu-22.04
    steps:
      - name:oku_app_name: boston-house-price-prediction1
          dockerfile_directory: ./
          dockerfile_name: Checkout
        uses: actions/checkout@v2

      - name Dockerfile
          docker_options: "--no-cache"
: Set Heroku stack to container
        run:          process_type: web

      - name: Set Heroku heroku stack:set container --app boston-house-price-p stack to container
        run: heroku stack:set container --app boston-house-price-prediction1

      -rediction1

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/her name: Release the Docker container
        run: heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_apioku container:release web --app boston-house-price-prediction1