name: Deploy to Heroku

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Step to set the Heroku stack to container
      - name: Set Heroku stack to container
        run: heroku stack:set container --app boston-house-price-prediction1

      # Build, Push and Release Docker container to Heroku
      - name: Build, Push and Release a Docker container to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: boston-house-price-prediction1
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web

      # Step to release the Docker container
      - name: Release the Docker container
        run: heroku container:release web --app boston-house-price-prediction1
